#!/usr/bin/env ruby
require 'optparse'
require File.expand_path('lib/boutique', File.dirname(__FILE__))
require 'dm-migrations'
require 'date'
require 'fileutils'

ENV['BOUTIQUE_CMD'] = '1'

module Boutique
  class Command
    def self.drip
      load_config
      Boutique::List.to_a.each do |list_key|
        emailer = Boutique::Emailer.new(List[list_key])
        emailer.drip
      end
    end

    def self.migrate
      load_config
      DataMapper.auto_upgrade!
    rescue DataObjects::SyntaxError => e
      DataMapper.auto_upgrade!
      load_config
    end

    private
    def self.load_config
      load(ENV['BOUTIQUE_CONFIG'] || 'config.ru')
    end
  end
end

ARGV.options do |o|
  o.set_summary_indent('  ')
  o.banner =    "Usage: #{File.basename($0)} [OPTION]"
  o.define_head "Admin for boutique"
  o.on('-d', '--drip', 'drip out emails') { Boutique::Command.drip; exit }
  o.on('-m', '--migrate', 'initial migration') { Boutique::Command.migrate; exit }
  o.on('-h', '--help', 'show this help message') { puts o; exit }
  o.parse!
  puts o
end
